### ISSUE TITLE
where is the ‘chenzhubing_20150627_train_1.cnt’?

### ISSUE THREAD

**Issue by geekchen007** [laubonghaudoi/CNN_P300#1]
请问在哪儿能获取到chenzhubing_20150627_train_1.cnt?

**Comment by laubonghaudoi** [comment]
.cnt文件是我自己采集的脑电波信号，这个代码下载之后不能直接运行，仅供参考。如果你想运行的话，可以参照README下的那篇论文，自己找第三次BCI竞赛的数据集，然后对应修改里面extractFeatures.m和Main.m读取数据部分的代码。

**Comment by mariafranciscva496** [comment]
> 请问在哪儿能获取到chenzhubing_20150627_train_1.cnt?
ElectricSquirrel did you manage change the code in order to function with the bci competition data set? thanks
